# Exact column mappings for Genesys interactions export dataset (45 columns)

# Metadata & Export Verification
FULL_EXPORT_COMPLETED_COL = "Full Export Completed"
PARTIAL_RESULT_TIMESTAMP_COL = "Partial Result Timestamp"
FILTERS_COL = "Filters"
TIMESTAMP_COL = "Date"
DURATION_COL = "Duration"

# Routing & Channels
MEDIA_TYPE_COL = "Media Type"
DIRECTION_COL = "Direction"
AGENT_COL = "Users"
REMOTE_COL = "Remote"
ANI_COL = "ANI"
DNIS_COL = "DNIS"
QUEUE_COL = "Queue"
FIRST_QUEUE_COL = "First Queue"
FLOW_COL = "Flow"
AUTHENTICATED_COL = "Authenticated"
HAS_CUSTOMER_JOURNEY_DATA_COL = "Has Customer Journey Data"

# Errors & Disconnect Reasons
DISCONNECT_TYPE_COL = "Disconnect Type"
ERROR_CODE_COL = "Error Code"
ERROR_COUNT_COL = "Error Count"
SYSTEM_ERROR_DISCONNECT_COL = "System Error Disconnect"
FLOW_DISCONNECT_COL = "Flow Disconnect"
ALL_FLOW_DISCONNECT_COL = "All Flow Disconnect"
CUSTOMER_DISCONNECT_COL = "Customer Disconnect"
CUSTOMER_SHORT_DISCONNECT_COL = "Customer Short Disconnect"
FLOW_EXIT_COL = "Flow Exit"
FLOW_OUT_TYPE_COL = "Flow-Out Type"

# Abandonment
ABANDONED_COL = "Abandoned"
ABANDONED_QUEUE_COL = "Abandoned in Queue"
TIME_TO_ABANDON_COL = "Time to Abandon"

# Performance & Timing (HH:MM:SS format)
TOTAL_IVR_COL = "Total IVR"
TOTAL_QUEUE_COL = "Total Queue"
TOTAL_HOLD_COL = "Total Hold"
TOTAL_HANDLE_COL = "Total Handle"

# Agent Activity & Exceptions
TRANSFERS_COL = "Transfers"
USERS_NOT_RESPONDING_COL = "Users - Not Responding"
NOT_RESPONDING_COL = "Not Responding"
BARGED_IN_COL = "Barged-In"

# Outcomes & Wrap-ups
WRAP_UP_COL = "Wrap-up"
OUTCOME_SUCCESS_COL = "Outcome Success"
OUTCOME_SUCCESS_PCT_COL = "Outcome Success %"
OUTCOME_FAILURE_COL = "Outcome Failure"
OUTCOME_FAILURE_PCT_COL = "Outcome Failure %"
FAILED_OUTCOMES_COL = "Failed Outcomes"
INCOMPLETE_OUTCOMES_COL = "Incomplete Outcomes"
IVR_SEGMENTS_COL = "IVR Segments"

# All 45 columns list
ALL_COLUMNS = [
    FULL_EXPORT_COMPLETED_COL, PARTIAL_RESULT_TIMESTAMP_COL, FILTERS_COL,
    MEDIA_TYPE_COL, AGENT_COL, REMOTE_COL, TIMESTAMP_COL, DURATION_COL,
    DIRECTION_COL, ANI_COL, DNIS_COL, QUEUE_COL, WRAP_UP_COL, ABANDONED_COL,
    FIRST_QUEUE_COL, ABANDONED_QUEUE_COL, FLOW_OUT_TYPE_COL, AUTHENTICATED_COL,
    ERROR_CODE_COL, IVR_SEGMENTS_COL, TIME_TO_ABANDON_COL, OUTCOME_SUCCESS_COL,
    OUTCOME_SUCCESS_PCT_COL, OUTCOME_FAILURE_COL, OUTCOME_FAILURE_PCT_COL,
    FLOW_EXIT_COL, ALL_FLOW_DISCONNECT_COL, CUSTOMER_DISCONNECT_COL,
    FLOW_DISCONNECT_COL, SYSTEM_ERROR_DISCONNECT_COL, FAILED_OUTCOMES_COL,
    INCOMPLETE_OUTCOMES_COL, CUSTOMER_SHORT_DISCONNECT_COL, FLOW_COL,
    HAS_CUSTOMER_JOURNEY_DATA_COL, DISCONNECT_TYPE_COL, USERS_NOT_RESPONDING_COL,
    BARGED_IN_COL, TOTAL_IVR_COL, TOTAL_QUEUE_COL, TOTAL_HOLD_COL,
    TOTAL_HANDLE_COL, TRANSFERS_COL, NOT_RESPONDING_COL, ERROR_COUNT_COL
]